name: "Terraform Plan"

on:
  pull_request:
  types: [opened, reopened]

jobs:
  terraform-apply-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: echo "Terraform Plan"
        