name: "Terraform Apply"

on:
  push:
    branches:
      - main

jobs:
  terraform-apply-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: echo "Terraform Apply"
        