name: "01-Terraform Plan"

on:
  pull_request:
    branches: main
    types: [opened, reopened]

jobs:
  terraform-plan-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: echo "Terraform Plan"
        